### ISSUE TITLE
Does this repo support fine-tuning large-v3 models?

### ISSUE THREAD

**Issue by hopto-dot** [saurastha/fine-tune-whisper#1]
There is a [difference](https://github.com/guillaumekln/faster-whisper/issues/547) in large-v2 and large-v3 models. I'm not sure if that makes a difference when fine-tuning though.

**Comment by saurastha** [comment]
After reviewing the large-v3 [documentation](https://huggingface.co/openai/whisper-large-v3), it appears that the fine-tuning process for the large-v3 model is consistent with previous versions. This repository is based on previous methods and  therefore supports the fine-tuning of large-v3 models based on this information.
